resources:
  - ../../base/loki-stack
  - loki-minio-secret.yaml

patches:
  - target:
      kind: HelmRelease
      name: loki
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: loki
      spec:
        values:
          loki:
            persistence:
              storageClass: nfs-rwx