apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
spec:
  capacity:
    storage: 3500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nextcloud-storage
  nfs:
    server: nas.internal
    path: /mnt/nextcloud/data
  mountOptions:
    - nfsvers=4.2
    - hard
