apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/loki-stack/loki-release.yaml
  - ../../base/loki-stack/promtail-release.yaml
  - ../../base/loki-stack/helmrepository.yaml

patches:
  - patch: |
      - op: replace
        path: /spec/values/loki/schemaConfig/configs/0/object_store
        value: filesystem
      - op: remove
        path: /spec/values/loki/storage
      - op: replace
        path: /spec/values/loki/persistence/size
        value: 5Gi
      - op: replace
        path: /spec/values/loki/limits_config/retention_period
        value: 3h
    target:
      kind: HelmRelease
      name: loki