apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrelease.yaml
  # - prometheusrules
  - secrets/grafana-admin-secret.enc.yaml
  #- servicemonitors

configMapGenerator:
  - name: k3s-monitoring-dashboard
    namespace: grafana
    files:
      - my-dashboard.json=dashboards/k3s-monitoring.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: flux-dashboards
    namespace: grafana
    files:
      - control-plane.json=dashboards/control-plane.json
      - cluster.json=dashboards/cluster.json
      - logs.json=dashboards/flux-logs.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: flux-kube-state-metrics-config
    namespace: monitoring
    files:
      - kube-state-metrics-config.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring

generatorOptions:
  disableNameSuffixHash: true

configurations:
  - kustomizeconfig.yaml
