apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cert-manager
  - ../base/metallb
  - helmreboot-operator
  - ../base/storage/nfs
  - cloudnative-pg
  - ingress-nginx
  - mariadb-operator
  - minio
