apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-1-pv
spec:
  capacity:
    storage: 45Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minio-storage
  nfs:
    server: nas.internal
    path: /mnt/minio1/data
  mountOptions:
    - nfsvers=4.2
    - hard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-2-pv
spec:
  capacity:
    storage: 45Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minio-storage
  nfs:
    server: nas.internal
    path: /mnt/minio1/data
  mountOptions:
    - nfsvers=4.2
    - hard