apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - helmrelease.yaml
  - clusterissuer.yaml

configMapGenerator:
  - name: cert-manager-values
    files:
      - values.yaml=values.yaml
generatorOptions:
  disableNameSuffixHash: true
