apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: local-charts
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/sfotiadis/flux-rpi-cluster
  branch: main
